Repository wecode-bootcamp-korea/48-2nd-Buster_Hot6-backend, pull requests merged in 2023-08, with the labels that each got.

#1 initial setting [김만규]
  .env.sample
  .gitignore
  app.js
  package-lock.json
  package.json
  src/models/data-source.js
Labels: 수정 요청

#4 [김만규]Feature/signup 회원가입/로그인 기능
  .env.sample
  app.js
  src/controllers/userControllers.js
  src/models/dataSource.js
  src/models/user.Dao.js
  src/routes/index.js
  src/routes/userRouter.js
  src/services/userServices.js
  src/utils/auth.js
  src/utils/error.js
  src/utils/validate.js
Labels: 멘토 리뷰 요청

#6 [김만규] migration 수정
  db/migrations/20230822065822_posts_scraps_table.sql
  db/migrations/20230822065823_products_scraps_table.sql
  db/migrations/20230822065825_refunds_table.sql
  db/migrations/20230822065826_reviews_table.sql
  db/migrations/20230825074620_modify_multiple_tables.sql
  src/models/dataSource.js
Labels: 멘토 리뷰 요청

#11 [김만규] products list 수정사항 완료
  app.js
  db/migrations/20230822065810_users_table.sql
  db/migrations/20230822065812_post_categories_table.sql
  src/controllers/productsControllers.js
  src/controllers/userControllers.js
  src/models/productsDao.js
  src/models/userDao.js
  src/routes/index.js
  src/routes/productsRoutes.js
  src/routes/userRouter.js
  src/services/productsServices.js
  src/services/userServices.js
  src/utils/auth.js
  src/utils/error.js
  src/utils/validate.js
Labels: 멘토 리뷰 요청

#14 [김시연] 장바구니 리스트 기능 구현
  app.js
  db/migrations/20230828070324_modify_multiple_tables.sql
  src/controllers/cartController.js
  src/controllers/productsControllers.js
  src/models/cartDao.js
  src/models/dataSource.js
  src/routes/cartRouter.js
  src/routes/index.js
  src/services/cartService.js
  src/services/userServices.js
  src/utils/auth.js
  src/utils/token.js
Labels: 수정 요청

#12 [김시연] product detail 기능 구현
  db/migrations/20230829072104_modify_reviews_tables.sql
  src/controllers/productsControllers.js
  src/models/productsDao.js
  src/routes/index.js
  src/routes/productsRouter.js
  src/routes/productsRoutes.js
  src/services/productsServices.js
Labels: 완료

#9 [김창현] Post & Product Scrap 기능 개발
  .env.sample
  app.js
  package-lock.json
  src/controllers/postController.js
  src/controllers/productsControllers.js
  src/models/postsDao.js
  src/models/productsDao.js
  src/routes/index.js
  src/routes/postsRouter.js
  src/routes/productsRouter.js
  src/services/postService.js
  src/services/productsServices.js
Labels: 멘토 리뷰 요청

#10 [김창현] 상품 리뷰 CRUD & 별점넣기 개발
  src/controllers/reviewsController.js
  src/models/reviewsDao.js
  src/routes/reviewsRouter.js
  src/services/reviewsService.js
Labels: 완료

#13 [최홍] product, post scrap 기능 구현
  src/controllers/postController.js
  src/controllers/productsControllers.js
  src/models/postsDao.js
  src/models/productsDao.js
  src/routes/index.js
  src/routes/postsRouter.js
  src/routes/productsRouter.js
  src/services/postService.js
  src/services/productsServices.js
Labels: 리뷰 진행 중

#16 [김시연]post detail 기능 구현
  src/controllers/postController.js
  src/models/postsDao.js
  src/services/postService.js
Labels: 멘토 리뷰 요청

#15 [김창현] Posts 메인페이지 정보 가져오기 기능.
  src/controllers/postController.js
  src/models/postsDao.js
  src/models/productsDao.js
  src/routes/index.js
  src/routes/postsRouter.js
  src/routes/productsRouter.js
  src/services/postService.js
Labels: 멘토 리뷰 요청
